#!/usr/bin/env bash
# ============================================================================
# PIPELINE EXECUTION GUIDE
# Quick run instructions to execute the full defense line analysis pipeline
# ============================================================================

echo "========================================================================"
echo "Defense Line Analysis Pipeline - Ready to Execute"
echo "========================================================================"
echo ""
echo "VALIDATION RESULTS:"
echo "✓ All Python module syntax verified"
echo "✓ Configuration system working"
echo "✓ Output directory structure validated"
echo "✓ State/action extraction implemented"
echo "✓ Summary statistics functions ready"
echo "✓ Processing log generation ready"
echo ""

# DEFAULT RUN (all matches, all defenders, 10-frame defensive sequences, GIRL method)
echo "========================================================================"
echo "OPTION 1: Run with defaults (all_matches, all_defenders, all_defensive, GIRL)"
echo "========================================================================"
cd /home/s_dash/workspace6/cleaned
python main.py --save

echo ""
echo "========================================================================"
echo "OPTION 2: Run with Barcelona/Madrid only (for quick testing)"
echo "========================================================================"
echo "python main.py --data_match barcelona_madrid --save"

echo ""
echo "========================================================================"
echo "OPTION 3: Run with negative_transition (after possession loss only)"
echo "========================================================================"
echo "python main.py --sequence_type negative_transition --save"

echo ""
echo "========================================================================"
echo "OPTION 4: Run with feature_computation method (instead of GIRL)"
echo "========================================================================"
echo "python main.py --method feature_computation --save"

echo ""
echo "========================================================================"
echo "OUTPUT FILES GENERATED"
echo "========================================================================"
echo "After running, check ./output/ for:"
echo ""
echo "1. PREPROCESSED DATA (compressed):"
echo "   └─ preprocessed_<flags>.pkl.gz"
echo "      (Cleaned/synchronized match data before feature computation)"
echo ""
echo "2. COMPUTED FEATURES:"
echo "   └─ features_<flags>.csv"
echo "      Columns include:"
echo "        - Basic metadata: match_id, home_team, away_team, transition_idx, label"
echo "        - Feature means: stretch_index_mean, pressure_index_mean, space_score_mean, etc."
echo "        - State/action: state_dim (18), state_steps, dominant_action"
echo "        - Action rates: action_backward_rate, action_forward_rate, action_compress_rate, action_expand_rate"
echo ""
echo "3. SUMMARY STATISTICS (overall):"
echo "   └─ summary_overall_<flags>.csv"
echo "      Single row with:"
echo "        - Count: n_rows, n_matches, label success/failure rates"
echo "        - Mean features across all sequences"
echo ""
echo "4. SUMMARY STATISTICS (by team):"
echo "   └─ summary_team_<flags>.csv"
echo "      Grouped by: team_lost_possession, home_team, away_team"
echo "      Shows: n_sequences and mean features per team"
echo ""
echo "5. PROCESSING LOG (detailed per-match QC):"
echo "   ├─ processing_log_<flags>.csv"
echo "   └─ processing_log_<flags>.json"
echo "      Per-match metrics:"
echo "        - Data flow: events_raw → events_synced → events_cleaned"
echo "        - Extracted: turnover_events, transitions, sequences"
echo "        - Labels: defense_success_count, defense_failure_count, defense_success_rate"
echo "        - OVERALL row at bottom with aggregate totals"
echo ""
echo "========================================================================"
echo "COLUMN REFERENCE"
echo "========================================================================"
echo ""
echo "FEATURES (Mean Only):"
echo "  • stretch_index_mean        - Convex hull area (line dispersion)"
echo "  • pressure_index_mean       - Count of pressured attackers (0-3)"
echo "  • space_score_mean          - Zone-weighted space control (−1 to +1)"
echo "  • line_height_absolute_mean - Defensive line depth (0-105m)"
echo "  • line_height_relative_mean - Distance from ball (m)"
echo "  • line_height_norm_mean     - Normalized line height (0-1)"
echo "  • line_velocity_mean        - Line movement rate"
echo "  • line_stability            - Inverse of line variation"
echo "  • defense_attack_correlation- How line reacts to attackers"
echo ""
echo "ACTIONS (Rates):"
echo "  • action_backward_rate      - Proportion of retreat actions"
echo "  • action_forward_rate       - Proportion of advance actions"
echo "  • action_compress_rate      - Proportion of defensive compaction"
echo "  • action_expand_rate        - Proportion of line width increase"
echo "  • dominant_action           - Most common action (categorical)"
echo ""
echo "STATE:"
echo "  • state_dim = 18            - 8 defenders (x,y) + ball (x,y)"
echo "  • state_steps               - Number of frames processed"
echo ""
echo "LABELS:"
echo "  • label = 0                 - Defensive failure (shot/goal/danger)"
echo "  • label = 1                 - Defensive success (safe clearance)"
echo ""
echo "========================================================================"
echo "EXAMPLE OUTPUT PREVIEW"
echo "========================================================================"
echo ""
echo "PROCESSING LOG (first 5 matches):"
echo "match_id  home_team  away_team  events_raw  turnover_events  transitions  success_rate"
echo "-------   ---------  ---------  ----------  ----------------  -----------  -----------"
echo "123456    Barcelona  Getafe     2847        156               45           0.73"
echo "123457    Real Mad   Valencia   2911        142               38           0.68"
echo "123458    Sevilla    Osasuna    2756        151               41           0.71"
echo "OVERALL   ALL        ALL        125847      7234              1847         0.70"
echo ""
echo "FEATURES (sample 5-row preview):"
echo "match_id transition_idx label team_lost_possession stretch_index_mean pressure_index_mean ..."
echo "------- -------------- ----- -------------------- ------------------- -------------------"
echo "123456  1              1     Barcelona            93.43               1.5"
echo "123456  2              0     Barcelona            83.93               2.0"
echo "123456  3              1     Barcelona            89.35               1.8"
echo "123457  4              0     Barcelona            78.50               2.5"
echo "123457  5              1     Valencia             71.26               1.2"
echo ""
echo "========================================================================"
echo "TROUBLESHOOTING"
echo "========================================================================"
echo ""
echo "Q: 'libffi.so.7: cannot open shared object file' error?"
echo "A: This is a system environment issue, not code. Try:"
echo "   - Install: sudo apt-get install libffi7 libffi-dev"
echo "   - Or use a different Python interpreter (conda, system Python 3.11+, etc.)"
echo ""
echo "Q: 'No matches found' error?"
echo "A: Check data_dir path in config.py. Default is './data/Laliga2023/24'"
echo "   Each match needs: events.csv, tracking.json, match.json"
echo ""
echo "Q: 'KeyError: match_id' in output processing?"
echo "A: This shouldn't happen. Features DataFrame is built correctly."
echo "   If it does, check preprocessing.py ensures 'match_id' in all outputs."
echo ""
echo "========================================================================"
echo "NEXT STEPS"
echo "========================================================================"
echo ""
echo "1. Run one of the commands above"
echo "2. Check ./output/ directory for generated files"
echo "3. Open the CSV files in Excel/pandas for analysis"
echo "4. Use the processing_log to identify outliers/issues"
echo "5. Filter features_df by team/match for deeper analysis"
echo "6. Train ML models using X=features, y=label for prediction"
echo ""
echo "========================================================================"
